CFLAGS=-Wall -std=c11

all: trial1 trial2 trial3

trial1: trial1.c
	gcc $(CFLAGS) -o $@ $<

trial2: trial2.c
	gcc $(CFLAGS) -o $@ $<

trial3: trial3.c
	gcc $(CFLAGS) -o $@ $<

clean:
	rm trial1 trial2 trial3
